"""Add background icon class attribute

Revision ID: 44087e15056f
Revises: 8f6ec009ef38
Create Date: 2025-12-02 00:41:04.495004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44087e15056f'
down_revision = '8f6ec009ef38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_background_class', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_item', schema=None) as batch_op:
        batch_op.drop_column('icon_background_class')

    # ### end Alembic commands ###
